Getting there.. All I need to run inside the Docker image is: `colcon build`
Then I get these errors:
```
--- stderr: neato_ros2_rust
error[E0432]: unresolved import `std_msgs`
 --> src/neato_ros2_rust.rs:2:5
  |
2 | use std_msgs;
  |     ^^^^^^^^ no external crate `std_msgs`

error[E0432]: unresolved import `sensor_msgs`
 --> src/neato_ros2_rust.rs:3:5
  |
3 | use sensor_msgs;
  |     ^^^^^^^^^^^ no external crate `sensor_msgs`

error[E0425]: cannot find type `RclResult` in crate `rclrs`
   --> src/neato_ros2_rust.rs:8:21
    |
  8 | fn main() -> rclrs::RclResult {
    |                     ^^^^^^^^^ help: a trait with a similar name exists: `ToResult`
    |
   ::: /root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rclrs-0.7.0/src/error.rs:544:1
    |
544 | pub(crate) trait ToResult {
    | ------------------------- similarly named trait `ToResult` defined here

error[E0599]: no method named `create_node` found for struct `rclrs::Context` in the current scope
  --> src/neato_ros2_rust.rs:11:24
   |
11 |     let node = context.create_node("neato")?;
   |                        ^^^^^^^^^^^ method not found in `rclrs::Context`

Some errors have detailed explanations: E0425, E0432, E0599.
For more information about an error, try `rustc --explain E0425`.
error: could not compile `neato_ros2_rust` (bin "neato_ros2_rust") due to 4 previous errors
```